expose max d0 setting
MuonColliderSoft/ACTSTracking pull request #8
Opened 2022-02-10 14:09 UTC by madbaron

Hi all,

This PR exposes the parameter regulating the maximum track d0 to allow dedicated long lived particle studies.
(And a bunch of whitespace changes made by VS code...)

Cheers,
Federico

2022-02-10 17:51 UTC, kkrizka requested changes

2022-02-10 17:51 UTC, kkrizka commented on src/ACTSSeededCKFTrackingProc.cxx
> +  finderCfg.impactMax = _CKF_d0CutOff;
`* Acts::UnitConstants::mm` to make the units explicit.

2022-02-10 17:51 UTC, kkrizka commented on ACTSTracking/ACTSSeededCKFTrackingProc.hxx
> +  double _CKF_d0CutOff = 3;
`* Acts::UnitConstants::mm` to set explicit units.

2022-02-11 08:42 UTC, madbaron commented
Hi @kkrizka,

I've implemented your suggestions (and now grouped the d0 cut together with the other seeding parameters).
In the original PR I didn't undo the white space changes, because I checked them and they all look for the better, but please insist if you disagree and I'll get rid of them!

2022-02-15 16:08 UTC, kkrizka commented on src/ACTSSeededCKFTrackingProc.cxx
> +  registerProcessorParameter("SeedFinding_impactMax",
Could you please upper case the first letter `"SeedFinding_ImpactMax"` for consistency with the other settings?

2022-02-15 16:18 UTC, kkrizka commented
Hi @madbaron ,

Code formatting is very subjective. Unless there is an official style being enforced by a CI, I would prefer that formatting changes are kept out of unrelated (to formatting) PR's.

Removing extra space at the end of a line and consistency changes are welcome though.

--
Karol Krizka

2022-03-30 14:40 UTC, madbaron commented
Finally coming back to this :D
I have capitalised the "I" as requested, as well as added an additional handle to steer the extrapolation direction.
@kkrizka, please have a look and let me know if you'd like me to make some other style change.

The only thing I didn't undo is the formatting cleanup, because I don't know how to do it :D

Cheers,
Federico

2022-05-10 08:15 UTC, kkrizka approved these changes

2022-05-10 08:16 UTC, merged